/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoIndexRouteImport } from './routes/atendimento.index'
import { Route as AtendimentoWhatsappRouteImport } from './routes/atendimento.whatsapp'
import { Route as AtendimentoUsuariosRouteImport } from './routes/atendimento.usuarios'
import { Route as AtendimentoTreinamentoRouteImport } from './routes/atendimento.treinamento'
import { Route as AtendimentoRespostasRouteImport } from './routes/atendimento.respostas'
import { Route as AtendimentoPropostasRouteImport } from './routes/atendimento.propostas'
import { Route as AtendimentoKanbanRouteImport } from './routes/atendimento.kanban'
import { Route as AtendimentoDashboardRouteImport } from './routes/atendimento.dashboard'
import { Route as AtendimentoContatosRouteImport } from './routes/atendimento.contatos'
import { Route as AtendimentoConfigRouteImport } from './routes/atendimento.config'
import { Route as ApiPublicProcessScheduledRouteImport } from './routes/api/public/process-scheduled'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicWapiWebhookRouteImport } from './routes/api/public/wapi.webhook'

const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIndexRoute = AtendimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoWhatsappRoute = AtendimentoWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoUsuariosRoute = AtendimentoUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoTreinamentoRoute = AtendimentoTreinamentoRouteImport.update({
  id: '/treinamento',
  path: '/treinamento',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoRespostasRoute = AtendimentoRespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoPropostasRoute = AtendimentoPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoKanbanRoute = AtendimentoKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoDashboardRoute = AtendimentoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoContatosRoute = AtendimentoContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AtendimentoRoute,
} as any)
const AtendimentoConfigRoute = AtendimentoConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AtendimentoRoute,
} as any)
const ApiPublicProcessScheduledRoute =
  ApiPublicProcessScheduledRouteImport.update({
    id: '/api/public/process-scheduled',
    path: '/api/public/process-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWapiWebhookRoute = ApiPublicWapiWebhookRouteImport.update({
  id: '/api/public/wapi/webhook',
  path: '/api/public/wapi/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRouteWithChildren
  '/login': typeof LoginRoute
  '/proposta': typeof PropostaRoute
  '/atendimento/config': typeof AtendimentoConfigRoute
  '/atendimento/contatos': typeof AtendimentoContatosRoute
  '/atendimento/dashboard': typeof AtendimentoDashboardRoute
  '/atendimento/kanban': typeof AtendimentoKanbanRoute
  '/atendimento/propostas': typeof AtendimentoPropostasRoute
  '/atendimento/respostas': typeof AtendimentoRespostasRoute
  '/atendimento/treinamento': typeof AtendimentoTreinamentoRoute
  '/atendimento/usuarios': typeof AtendimentoUsuariosRoute
  '/atendimento/whatsapp': typeof AtendimentoWhatsappRoute
  '/atendimento/': typeof AtendimentoIndexRoute
  '/api/public/process-scheduled': typeof ApiPublicProcessScheduledRoute
  '/api/public/wapi/webhook': typeof ApiPublicWapiWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proposta': typeof PropostaRoute
  '/atendimento/config': typeof AtendimentoConfigRoute
  '/atendimento/contatos': typeof AtendimentoContatosRoute
  '/atendimento/dashboard': typeof AtendimentoDashboardRoute
  '/atendimento/kanban': typeof AtendimentoKanbanRoute
  '/atendimento/propostas': typeof AtendimentoPropostasRoute
  '/atendimento/respostas': typeof AtendimentoRespostasRoute
  '/atendimento/treinamento': typeof AtendimentoTreinamentoRoute
  '/atendimento/usuarios': typeof AtendimentoUsuariosRoute
  '/atendimento/whatsapp': typeof AtendimentoWhatsappRoute
  '/atendimento': typeof AtendimentoIndexRoute
  '/api/public/process-scheduled': typeof ApiPublicProcessScheduledRoute
  '/api/public/wapi/webhook': typeof ApiPublicWapiWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRouteWithChildren
  '/login': typeof LoginRoute
  '/proposta': typeof PropostaRoute
  '/atendimento/config': typeof AtendimentoConfigRoute
  '/atendimento/contatos': typeof AtendimentoContatosRoute
  '/atendimento/dashboard': typeof AtendimentoDashboardRoute
  '/atendimento/kanban': typeof AtendimentoKanbanRoute
  '/atendimento/propostas': typeof AtendimentoPropostasRoute
  '/atendimento/respostas': typeof AtendimentoRespostasRoute
  '/atendimento/treinamento': typeof AtendimentoTreinamentoRoute
  '/atendimento/usuarios': typeof AtendimentoUsuariosRoute
  '/atendimento/whatsapp': typeof AtendimentoWhatsappRoute
  '/atendimento/': typeof AtendimentoIndexRoute
  '/api/public/process-scheduled': typeof ApiPublicProcessScheduledRoute
  '/api/public/wapi/webhook': typeof ApiPublicWapiWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/login'
    | '/proposta'
    | '/atendimento/config'
    | '/atendimento/contatos'
    | '/atendimento/dashboard'
    | '/atendimento/kanban'
    | '/atendimento/propostas'
    | '/atendimento/respostas'
    | '/atendimento/treinamento'
    | '/atendimento/usuarios'
    | '/atendimento/whatsapp'
    | '/atendimento/'
    | '/api/public/process-scheduled'
    | '/api/public/wapi/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/proposta'
    | '/atendimento/config'
    | '/atendimento/contatos'
    | '/atendimento/dashboard'
    | '/atendimento/kanban'
    | '/atendimento/propostas'
    | '/atendimento/respostas'
    | '/atendimento/treinamento'
    | '/atendimento/usuarios'
    | '/atendimento/whatsapp'
    | '/atendimento'
    | '/api/public/process-scheduled'
    | '/api/public/wapi/webhook'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/login'
    | '/proposta'
    | '/atendimento/config'
    | '/atendimento/contatos'
    | '/atendimento/dashboard'
    | '/atendimento/kanban'
    | '/atendimento/propostas'
    | '/atendimento/respostas'
    | '/atendimento/treinamento'
    | '/atendimento/usuarios'
    | '/atendimento/whatsapp'
    | '/atendimento/'
    | '/api/public/process-scheduled'
    | '/api/public/wapi/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PropostaRoute: typeof PropostaRoute
  ApiPublicProcessScheduledRoute: typeof ApiPublicProcessScheduledRoute
  ApiPublicWapiWebhookRoute: typeof ApiPublicWapiWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/': {
      id: '/atendimento/'
      path: '/'
      fullPath: '/atendimento/'
      preLoaderRoute: typeof AtendimentoIndexRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/whatsapp': {
      id: '/atendimento/whatsapp'
      path: '/whatsapp'
      fullPath: '/atendimento/whatsapp'
      preLoaderRoute: typeof AtendimentoWhatsappRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/usuarios': {
      id: '/atendimento/usuarios'
      path: '/usuarios'
      fullPath: '/atendimento/usuarios'
      preLoaderRoute: typeof AtendimentoUsuariosRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/treinamento': {
      id: '/atendimento/treinamento'
      path: '/treinamento'
      fullPath: '/atendimento/treinamento'
      preLoaderRoute: typeof AtendimentoTreinamentoRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/respostas': {
      id: '/atendimento/respostas'
      path: '/respostas'
      fullPath: '/atendimento/respostas'
      preLoaderRoute: typeof AtendimentoRespostasRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/propostas': {
      id: '/atendimento/propostas'
      path: '/propostas'
      fullPath: '/atendimento/propostas'
      preLoaderRoute: typeof AtendimentoPropostasRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/kanban': {
      id: '/atendimento/kanban'
      path: '/kanban'
      fullPath: '/atendimento/kanban'
      preLoaderRoute: typeof AtendimentoKanbanRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/dashboard': {
      id: '/atendimento/dashboard'
      path: '/dashboard'
      fullPath: '/atendimento/dashboard'
      preLoaderRoute: typeof AtendimentoDashboardRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/contatos': {
      id: '/atendimento/contatos'
      path: '/contatos'
      fullPath: '/atendimento/contatos'
      preLoaderRoute: typeof AtendimentoContatosRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/atendimento/config': {
      id: '/atendimento/config'
      path: '/config'
      fullPath: '/atendimento/config'
      preLoaderRoute: typeof AtendimentoConfigRouteImport
      parentRoute: typeof AtendimentoRoute
    }
    '/api/public/process-scheduled': {
      id: '/api/public/process-scheduled'
      path: '/api/public/process-scheduled'
      fullPath: '/api/public/process-scheduled'
      preLoaderRoute: typeof ApiPublicProcessScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wapi/webhook': {
      id: '/api/public/wapi/webhook'
      path: '/api/public/wapi/webhook'
      fullPath: '/api/public/wapi/webhook'
      preLoaderRoute: typeof ApiPublicWapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AtendimentoRouteChildren {
  AtendimentoConfigRoute: typeof AtendimentoConfigRoute
  AtendimentoContatosRoute: typeof AtendimentoContatosRoute
  AtendimentoDashboardRoute: typeof AtendimentoDashboardRoute
  AtendimentoKanbanRoute: typeof AtendimentoKanbanRoute
  AtendimentoPropostasRoute: typeof AtendimentoPropostasRoute
  AtendimentoRespostasRoute: typeof AtendimentoRespostasRoute
  AtendimentoTreinamentoRoute: typeof AtendimentoTreinamentoRoute
  AtendimentoUsuariosRoute: typeof AtendimentoUsuariosRoute
  AtendimentoWhatsappRoute: typeof AtendimentoWhatsappRoute
  AtendimentoIndexRoute: typeof AtendimentoIndexRoute
}

const AtendimentoRouteChildren: AtendimentoRouteChildren = {
  AtendimentoConfigRoute: AtendimentoConfigRoute,
  AtendimentoContatosRoute: AtendimentoContatosRoute,
  AtendimentoDashboardRoute: AtendimentoDashboardRoute,
  AtendimentoKanbanRoute: AtendimentoKanbanRoute,
  AtendimentoPropostasRoute: AtendimentoPropostasRoute,
  AtendimentoRespostasRoute: AtendimentoRespostasRoute,
  AtendimentoTreinamentoRoute: AtendimentoTreinamentoRoute,
  AtendimentoUsuariosRoute: AtendimentoUsuariosRoute,
  AtendimentoWhatsappRoute: AtendimentoWhatsappRoute,
  AtendimentoIndexRoute: AtendimentoIndexRoute,
}

const AtendimentoRouteWithChildren = AtendimentoRoute._addFileChildren(
  AtendimentoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRouteWithChildren,
  LoginRoute: LoginRoute,
  PropostaRoute: PropostaRoute,
  ApiPublicProcessScheduledRoute: ApiPublicProcessScheduledRoute,
  ApiPublicWapiWebhookRoute: ApiPublicWapiWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
