/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropostaRouteImport } from './routes/proposta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoIndexRouteImport } from './routes/atendimento.index'

const PropostaRoute = PropostaRouteImport.update({
  id: '/proposta',
  path: '/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIndexRoute = AtendimentoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtendimentoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRouteWithChildren
  '/login': typeof LoginRoute
  '/proposta': typeof PropostaRoute
  '/atendimento/': typeof AtendimentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/proposta': typeof PropostaRoute
  '/atendimento': typeof AtendimentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRouteWithChildren
  '/login': typeof LoginRoute
  '/proposta': typeof PropostaRoute
  '/atendimento/': typeof AtendimentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atendimento' | '/login' | '/proposta' | '/atendimento/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/proposta' | '/atendimento'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/login'
    | '/proposta'
    | '/atendimento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRouteWithChildren
  LoginRoute: typeof LoginRoute
  PropostaRoute: typeof PropostaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposta': {
      id: '/proposta'
      path: '/proposta'
      fullPath: '/proposta'
      preLoaderRoute: typeof PropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/': {
      id: '/atendimento/'
      path: '/'
      fullPath: '/atendimento/'
      preLoaderRoute: typeof AtendimentoIndexRouteImport
      parentRoute: typeof AtendimentoRoute
    }
  }
}

interface AtendimentoRouteChildren {
  AtendimentoIndexRoute: typeof AtendimentoIndexRoute
}

const AtendimentoRouteChildren: AtendimentoRouteChildren = {
  AtendimentoIndexRoute: AtendimentoIndexRoute,
}

const AtendimentoRouteWithChildren = AtendimentoRoute._addFileChildren(
  AtendimentoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRouteWithChildren,
  LoginRoute: LoginRoute,
  PropostaRoute: PropostaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
